/**
 * Diagram storage service using Go gateway backend
 * Handles saving, loading, listing, and deleting diagram data via REST API.
 * When the backend returns an error, diagrams are stored in localStorage as a fallback.
 */

const LOCAL_STORAGE_KEY = "spasdacs_diagrams_local";
const AUTOVIEW_CACHE_KEY = "spasdacs_autoview_cache";

/**
 * Full diagram data cache for auto-view mode.
 * Populated on first visit to each diagram within a session; cleared whenever
 * auto-view is started so the session always begins with fresh data.
 * No TTL — the cache is permanent within a session and only invalidated
 * explicitly (auto-view start, diagram save, diagram delete).
 */
const DIAGRAM_FULL_CACHE_KEY = "spasdacs_diagram_full_cache";

export interface ViewportState {
  /** Zoom scale (e.g. 0.8 = 80%) */
  zoom: number;
  /** Center of the viewport in graph local coordinates */
  cx: number;
  cy: number;
}

/**
 * Telemetry input manifest for a diagram, generated by the gateway at save time.
 * Mirrors the Go models.TelemetryManifest shape.
 */
export interface TelemetryManifest {
  /** Bare paramIds bound directly or via literal TM[] script references. */
  params: string[];
  /** sourceStreamIds referenced by scoped/script bindings. */
  chains: string[];
  /** True if any __multi__/transform script is present (informational). */
  hasScripts: boolean;
  /** True if a binding reads the whole TM map → viewer must use the firehose. */
  needsFull: boolean;
}

export interface DiagramData {
  id: string;
  name: string;
  description?: string;
  modelData: string | Record<string, unknown>; // JSON stringified GoJS model (legacy) or object
  /**
   * View-mode optimised copy of modelData generated at save time.
   * All binding topics and TM[] script references are reduced to bare paramIds
   * (e.g. "RFS00057_5W_SSPA1-ON-OFF_STS" → "RFS00057") so the viewer can match
   * incoming NATS messages directly without loading the gateway mnemonic mapping.
   * Present on diagrams saved after this feature was introduced; absent on older
   * diagrams (viewer falls back to modelData + runtime translation in that case).
   */
  viewModelData?: string;
  /**
   * Telemetry inputs this diagram consumes, computed server-side at save time.
   * Lets the viewer subscribe to only the paramIds it binds (per-param NATS
   * subjects) instead of the full firehose. `needsFull` means a binding reads
   * the whole TM map (dynamic/unscoped script) so the viewer must fall back to
   * the unified subject. Absent on diagrams saved before this feature.
   */
  telemetryManifest?: TelemetryManifest;
  backgroundColor?: string; // Canvas background color
  canvasSize?: string;       // e.g. "1920x1080" | "infinite"
  createdAt: string;
  updatedAt: string;
  /** Whether this diagram participates in Auto View cycling (default: true) */
  autoViewInclude?: boolean;
  /** Seconds to display this diagram during Auto View cycling (default: 30) */
  autoViewDuration?: number;
  /** Last saved pan/zoom state for the viewer canvas */
  viewportState?: ViewportState;
  /** Global default connector stroke colour */
  edgeColor?: string;
  /** Global default connector stroke width */
  edgeWidth?: number;
  /** Multiplier applied to the larger node dimension to compute port radius on resize.
   *  Default 0.12. Stored per-diagram so each diagram can tune its own port sizes. */
  portSizeFactor?: number;
}

function getDiagramApiBaseUrl(): string {
  const fallback = `http://${import.meta.env.DEV ? window.location.hostname : window.location.host}/api/go/v1`;
  const configured =
    (import.meta.env.VITE_DIAGRAM_API_URL as string | undefined) ??
    (import.meta.env.VITE_GATEWAY_URL as string | undefined) ??
    fallback;
  return configured.trim().replace(/\/+$/, "");
}

/** API is routed via Kong gateway (default port 8000, prefix /gateway). */
function getDiagramApiBaseCandidates(): string[] {
  return [getDiagramApiBaseUrl()];
}

async function fetchWithDiagramApiFallback(path: string, init?: RequestInit): Promise<Response> {
  const candidates = getDiagramApiBaseCandidates();
  let lastError: unknown;

  for (const base of candidates) {
    const url = `${base}${path}`;
    try {
      const response = await fetch(url, init);
      if (response.ok || response.status !== 404) {
        return response;
      }
      lastError = new Error(`HTTP ${response.status} at ${url}`);
    } catch (error) {
      lastError = error;
    }
  }

  throw lastError ?? new Error("Diagram API request failed");
}

/** Read fallback map from localStorage */
function getLocalFallbackMap(): Record<string, DiagramData> {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw) as Record<string, DiagramData>;
    return typeof parsed === "object" && parsed !== null ? parsed : {};
  } catch {
    return {};
  }
}

/** Write one diagram to the fallback map and persist */
function setLocalFallback(diagram: DiagramData): void {
  const map = getLocalFallbackMap();
  map[diagram.id] = diagram;
  try {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(map));
  } catch (e) {
    console.error("[DiagramStorage] Failed to write localStorage fallback:", e);
  }
}

// ── autoview local cache (survives backend failures) ────────────────────────

type AutoViewCache = Record<string, { autoViewInclude?: boolean; autoViewDuration?: number }>;

function getAutoViewCache(): AutoViewCache {
  try {
    const raw = localStorage.getItem(AUTOVIEW_CACHE_KEY);
    if (!raw) return {};
    return JSON.parse(raw) as AutoViewCache;
  } catch { return {}; }
}

function setAutoViewCache(id: string, fields: { autoViewInclude?: boolean; autoViewDuration?: number }): void {
  try {
    const cache = getAutoViewCache();
    cache[id] = { ...cache[id], ...fields };
    localStorage.setItem(AUTOVIEW_CACHE_KEY, JSON.stringify(cache));
  } catch { /* ignore */ }
}

function removeAutoViewCache(id: string): void {
  try {
    const cache = getAutoViewCache();
    delete cache[id];
    localStorage.setItem(AUTOVIEW_CACHE_KEY, JSON.stringify(cache));
  } catch { /* ignore */ }
}

// ── Full diagram data cache (for auto-view mode) ─────────────────────────────
//
// Intentionally in-memory (not localStorage).
// Diagram JSON including modelData can be hundreds of KB each; a multi-diagram
// installation would quickly exceed the 5–10 MB localStorage quota, causing
// setItem to throw and silently fall back to no caching at all.
// An in-memory Map has no quota, no JSON serialisation cost, and is cleared
// automatically when the page unloads — exactly the lifetime we need.
// The constant DIAGRAM_FULL_CACHE_KEY is kept so existing code that may have
// written a value to localStorage is cleaned up on first load.

const _diagramAutoViewCache = new Map<string, DiagramData>();

// Tracks fetches that are currently in flight, keyed by diagram id. When
// auto-view starts we pre-fetch every included diagram in parallel and the
// first cycle hops can fire before any of those resolve. Without dedup each of
// those concurrent callers would launch its own /diagrams/{id} request, which
// looks (and behaves) like "hitting the backend on every cycle". Sharing one
// promise per id means at most ONE backend request per diagram per session.
const _diagramAutoViewInflight = new Map<string, Promise<DiagramData | null>>();

// Clean up any stale localStorage entry left by the previous implementation.
try { localStorage.removeItem(DIAGRAM_FULL_CACHE_KEY); } catch { /* ignore */ }

function setCachedDiagram(diagram: DiagramData): void {
  _diagramAutoViewCache.set(diagram.id, diagram);
}

function getCachedDiagram(id: string): DiagramData | null {
  return _diagramAutoViewCache.get(id) ?? null;
}

function clearAllCachedDiagrams(): void {
  _diagramAutoViewCache.clear();
  _diagramAutoViewInflight.clear();
}

function evictCachedDiagram(id: string): void {
  _diagramAutoViewCache.delete(id);
  _diagramAutoViewInflight.delete(id);
}

/** Remove one diagram from the fallback map */
function removeLocalFallback(id: string): void {
  const map = getLocalFallbackMap();
  delete map[id];
  try {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(map));
  } catch (e) {
    console.error("[DiagramStorage] Failed to update localStorage fallback:", e);
  }
}

export class DiagramStorage {
  /**
   * Get all saved diagrams (metadata only). Backend first; on failure returns local fallback only.
   */
  static async getAllDiagrams(): Promise<DiagramData[]> {
    try {
      const response = await fetchWithDiagramApiFallback("/diagrams");
      if (!response.ok) throw new Error("Failed to fetch diagrams");
      const fromBackend = await response.json();
      const localMap = getLocalFallbackMap();
      const avCache = getAutoViewCache();
      const backendIds = new Set((fromBackend as DiagramData[]).map((d) => d.id));
      const localOnly = Object.values(localMap).filter((d) => !backendIds.has(d.id));
      // Merge locally-cached autoview overrides onto backend diagrams
      const merged = (fromBackend as DiagramData[]).map((d) => {
        const av = avCache[d.id];
        if (!av) return d;
        return {
          ...d,
          autoViewInclude:  d.autoViewInclude  ?? av.autoViewInclude,
          autoViewDuration: d.autoViewDuration ?? av.autoViewDuration,
        };
      });
      return [...merged, ...localOnly];
    } catch (e) {
      console.warn("[DiagramStorage] Backend list failed, using local fallback:", e);
      return Object.values(getLocalFallbackMap());
    }
  }

  /**
   * Get a single diagram by ID (with full data). Backend first; on failure or 404, tries local fallback.
   * Pass `viewOnly = true` to request the view-optimised payload (no modelData): saves ~240 KB per fetch
   * because the server strips the raw modelData field when viewModelData is present.
   */
  static async getDiagram(id: string, viewOnly = false): Promise<DiagramData | null> {
    const path = viewOnly ? `/diagrams/${id}?slim=view` : `/diagrams/${id}`;
    try {
      const response = await fetchWithDiagramApiFallback(path);
      if (!response.ok) {
        if (response.status === 404) {
          const local = getLocalFallbackMap()[id];
          if (local) return local;
          return null;
        }
        throw new Error("Failed to fetch diagram");
      }
      const data = await response.json();
      return data;
    } catch (e) {
      console.warn("[DiagramStorage] Backend fetch failed, trying local fallback:", e);
      const local = getLocalFallbackMap()[id];
      if (local) {
        return local;
      }
      return null;
    }
  }

  /**
   * Save or update a diagram. Tries backend first; on error saves to localStorage and returns local copy.
   */
  static async saveDiagram(diagram: Omit<DiagramData, "createdAt" | "updatedAt">): Promise<DiagramData> {
    const now = new Date().toISOString();
    const withTimestamps: DiagramData = {
      ...diagram,
      createdAt: (diagram as DiagramData).createdAt ?? now,
      updatedAt: now,
    };

    try {
      const apiBases = getDiagramApiBaseCandidates();
      const response = await fetchWithDiagramApiFallback("/diagrams", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(diagram),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.warn(`[DiagramStorage] Save failed: ${response.status}, using local fallback - ${errorText}`);
        setLocalFallback(withTimestamps);
        return withTimestamps;
      }
      const saved = await response.json();
      return saved;
    } catch (e) {
      console.warn("[DiagramStorage] Backend save failed, storing in browser:", e);
      setLocalFallback(withTimestamps);
      return withTimestamps;
    }
  }

  /**
   * Partially update a diagram's fields (e.g. autoViewInclude, autoViewDuration, viewportState).
   * Uses PATCH to avoid sending the full modelData payload.
   */
  static async patchDiagram(id: string, fields: Partial<Pick<DiagramData, "autoViewInclude" | "autoViewDuration" | "viewportState">>): Promise<boolean> {
    // Always persist locally first so a backend failure doesn't lose the change
    setAutoViewCache(id, fields);
    try {
      const response = await fetchWithDiagramApiFallback(`/diagrams/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(fields),
      });
      if (!response.ok) {
        console.warn(`[DiagramStorage] Patch failed: ${response.status} — saved locally`);
        return false;
      }
      return true;
    } catch (e) {
      console.warn("[DiagramStorage] Backend patch failed — saved locally:", e);
      return false;
    }
  }

  /**
   * Delete a diagram by ID. Removes from backend and from local fallback.
   */
  static async deleteDiagram(id: string): Promise<boolean> {
    try {
      const response = await fetchWithDiagramApiFallback(`/diagrams/${id}`, {
        method: "DELETE",
      });
      if (!response.ok) {
        if (response.status === 404) {
          removeLocalFallback(id);
          return true;
        }
        throw new Error("Failed to delete diagram");
      }
      removeLocalFallback(id);
      removeAutoViewCache(id);
      evictCachedDiagram(id);
      return true;
    } catch (e) {
      console.warn("[DiagramStorage] Backend delete failed, removing from local only:", e);
      removeLocalFallback(id);
      removeAutoViewCache(id);
      evictCachedDiagram(id);
      return true;
    }
  }

  /**
   * Get a single diagram for auto-view cycling.
   * Checks the localStorage full-diagram cache first (TTL: 5 minutes) to avoid
   * a backend round-trip on every auto-view hop. Falls back to getDiagram() on
   * cache miss, and stores the result for the next cycle.
   */
  static async getForAutoView(id: string): Promise<DiagramData | null> {
    // 1. Already cached → no network at all.
    const cached = getCachedDiagram(id);
    if (cached) return cached;

    // 2. A fetch for this id is already running (e.g. startAutoView's parallel
    //    pre-fetch). Reuse it instead of launching a duplicate request.
    const inflight = _diagramAutoViewInflight.get(id);
    if (inflight) return inflight;

    // 3. Cold — fetch once, populate the cache keyed by the REQUEST id (so a
    //    cache read with the same id is guaranteed to hit), and share the
    //    promise with any concurrent callers until it settles.
    const p = this.getDiagram(id, true).then((diagram) => {
      if (diagram) _diagramAutoViewCache.set(id, diagram);
      return diagram;
    }).finally(() => {
      _diagramAutoViewInflight.delete(id);
    });
    _diagramAutoViewInflight.set(id, p);
    return p;
  }

  /**
   * Invalidate the full-diagram cache entry for a given ID.
   * Called after saving so the viewer picks up the latest version on the
   * next auto-view hop instead of serving the stale cached copy.
   */
  static invalidateDiagramCache(id: string): void {
    evictCachedDiagram(id);
  }

  /**
   * Clear the entire full-diagram cache.
   * Call this when auto-view starts so the session always begins with
   * fresh data fetched from the backend.
   */
  static clearDiagramCache(): void {
    clearAllCachedDiagrams();
  }

  /** NATS server connection status payload. */
  static async getNatsStatus(): Promise<{ connections: number; max: number } | null> {
    try {
      const base = getDiagramApiBaseUrl();
      const resp = await fetch(`${base}/nats/status`, { signal: AbortSignal.timeout(1_500) });
      if (!resp.ok) return null;
      return await resp.json() as { connections: number; max: number };
    } catch {
      return null;
    }
  }

  /**
   * Generate a unique ID for a new diagram
   */
  static generateId(): string {
    return `diagram_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  /**
   * Export diagram as JSON for download.
   * viewModelData is stripped — it is a server-generated derivative of
   * modelData and is regenerated automatically on every POST save, so it
   * does not belong in portable export files.
   */
  static exportDiagram(diagram: DiagramData): string {
    // viewModelData and telemetryManifest are server-generated derivatives of
    // modelData (regenerated on every POST save), so they don't belong in
    // portable export files.
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { viewModelData: _vm, telemetryManifest: _tm, ...exportable } = diagram;
    return JSON.stringify(exportable, null, 2);
  }

  /**
   * Import diagram from JSON string
   */
  static async importDiagram(jsonString: string): Promise<DiagramData | null> {
    try {
      const diagram = JSON.parse(jsonString) as DiagramData;
      // Validate required fields
      if (!diagram.id || !diagram.name || !diagram.modelData) {
        return null;
      }
      return await this.saveDiagram(diagram);
    } catch (e) {
      console.error('Failed to import diagram:', e);
      return null;
    }
  }
}
