routes:
  - id: spa
    uri: /*
    upstream:
      type: roundrobin
      nodes:
        "spa:80": 1

  - id: gateway-api
    uri: /api/*
    plugins:
      openid-connect:
        client_id: apisix-introspection
        client_secret: apisix-introspection-secret-change-me
        discovery: http://keycloak:8080/realms/scg/.well-known/openid-configuration
        bearer_only: true
        realm: scg
    upstream:
      type: roundrobin
      nodes:
        "gateway:21000": 1

  - id: gateway-restapi
    uri: /restApi/*
    plugins:
      openid-connect:
        client_id: apisix-introspection
        client_secret: apisix-introspection-secret-change-me
        discovery: http://keycloak:8080/realms/scg/.well-known/openid-configuration
        bearer_only: true
        realm: scg
    upstream:
      type: roundrobin
      nodes:
        "gateway:21000": 1

  - id: simulator
    uri: /simulator/*
    plugins:
      openid-connect:
        client_id: apisix-introspection
        client_secret: apisix-introspection-secret-change-me
        discovery: http://keycloak:8080/realms/scg/.well-known/openid-configuration
        bearer_only: true
        realm: scg
    upstream:
      type: roundrobin
      nodes:
        "simulator:21001": 1

  - id: umacs
    uri: /umacs/*
    plugins:
      openid-connect:
        client_id: apisix-introspection
        client_secret: apisix-introspection-secret-change-me
        discovery: http://keycloak:8080/realms/scg/.well-known/openid-configuration
        bearer_only: true
        realm: scg
    upstream:
      type: roundrobin
      nodes:
        "umacs-tc:21002": 1

  - id: nats-ws
    uri: /nats*
    enable_websocket: true
    upstream:
      type: roundrobin
      nodes:
        "nats:4223": 1

#END
